{
 "title": "Jenkins metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Jenkins last build result",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_result"
    }
   ]
  },
  {
   "title": "Jenkins last build duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds / 1000000"
    }
   ]
  },
  {
   "title": "Jenkins last build tests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_tests_total"
    }
   ]
  },
  {
   "title": "Jenkins uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_uptime / 1000000"
    }
   ]
  }
 ]
}