pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/Hunterszone/MyJavaGames.git'

                // Run Maven on a Unix agent.
                // sh "mvn -Dmaven.test.failure.ignore=true clean package"

                // To run Maven on a Windows agent, use
                bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/Snake/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts '**/Snake/target/*.jar'
                }
            }
        }
        stage('Deploy') {
            steps {
                withMaven(maven: 'M3', mavenSettingsConfig: 'd814f7db-b5d8-4373-9b57-d201ed66f6b5') {
                    // To run Maven on a Windows agent, use
                    bat "mvn -Dmaven.test.failure.ignore=true clean deploy"
                }
            }
        }
    }
}
